#!/bin/bash

banner()
{
    printf "Tools required:\n"
    printf "    - Stylus on firefox\n"
    printf "    - An epitech.eu email\n\n"
    generate
}

generate()
{
    input="config.ini"
    output="style.css"

    if [[ -f $input ]]; then
        printf "Config file........: FOUND\n"
    else
        printf "Config file........: NOT FOUND\n"
        exit
    fi

    while IFS= read -r line
    do
        if [[ $line = "PROFILE="* ]]; then
            profile=$(echo $line | cut -d '=' -f 2)
            printf "Profile picture: $profile\n"
        fi
        if [[ $line == "COLOR="* ]]; then
            color=$(echo $line | cut -d '=' -f 2)
            printf "Main color: $color\n"

        fi
        if [[ $line == "HEADER="* ]]; then
            header=$(echo $line | cut -d '=' -f 2)
            printf "Header: $header\n"
        fi
        if [[ $line == "GPA="* ]]; then
            gpa=$(echo $line | cut -d '=' -f 2)
            printf "Gpa: $gpa\n"
        fi
    done < "$input"

    echo "    /* No Stress Intranet
    ** Remove all this useless sh*t !
    ** By HentaiShiroYuki
    ** Generated with PIMP MY INTRA
    */ 
     
    /* Variables */
    :root
    {
        /*Changer cette url pour changer la photo de profil*/
        --custom-profile-picture: $profile;
        /*Changer cette url pour changer le bouton de login*/
        --custom-login-button: $profile;
    }
    
    /* Repositionne le bouton de login pour certains appareils linux */
    #auth-login .slider
    {
        width: auto;
    }
    
    /* Change l'image du bouton de login */
    #auth-login .login-student a
    {
        background: center center var(--custom-login-button);
        background-size: cover;
    }
    
    /* Hide GPA */
    div .rzone
    {
        display: none;
    }
    
    /* Change la photo de profil */
    .picture
    {
        background:left center var(--custom-profile-picture) !important;
        background-size: 100% 100% !important;
    }
    
    /* Some more magic */
     .picture img,
    #profil .bloc.main .data .picture img
    {
        display: none;
    }
    
    /* Even more magic */
    #header #notification .dropdown.pedago
    {
        display: none;
    }
    
    /* MAIN HEADER */
    #header .header-wrapper
    {
        background-image: $header !important;
        background-repeat: no-repeat;
        background-size: 100%;
    }
    
    /* BOX BACKGROUND*/
    section
    {
        background: $color !important;
    }
    
    #content
    {
        background: $color !important;
    }
    
    #sidebar
    {
        background: $color !important;
    }" > $output

}

banner
